name: Build

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Enable Corepack
      run: corepack enable

    - name: Set yarn version
      run: yarn set version self

    - name: Install dependencies
      run: yarn install

    - name: Run build
      run: yarn build
