name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: 'node'
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name : Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        if: ${{ steps.release.outputs.release_created }}
      - name: Enable Corepack
        run: corepack enable
        if: ${{ steps.release.outputs.release_created }}
      - name: Set yarn version
        run: yarn set version self
        if: ${{ steps.release.outputs.release_created }}
      - name: Install dependencies
        run: yarn install
        if: ${{ steps.release.outputs.release_created }}
      - name: Run publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
